package constants

const (
	COMMUNICATION_AUDIENCE_ALL      = "school"
	COMMUNICATION_AUDIENCE_DIRECTOR = "director"
	COMMUNICATION_AUDIENCE_TEACHER  = "teacher"
	COMMUNICATION_AUDIENCE_STUDENT  = "student"
	COMMUNICATION_AUDIENCE_PARENT   = "parent"
)
