package constants

const (
	PermissionCreate = "c"
	PermissionRead   = "r"
	PermissionUpdate = "u"
	PermissionDelete = "d"
)

const (
	FeatureAdmin    = "dashboard-admin"
	FeatureDirector = "dashboard-director"
	FeatureTeacher  = "dashboard-teacher"
	FeatureStudent  = "dashboard-student"
	FeatureParent   = "dashboard-parent"

	FeatureDefault = "dashboard-default"
)

const (
	// All
	RESOURCE_TABLE_ALL = "*"

	// Other
	RESOURCE_TABLE_COMMUNICATION = "communications"
	RESOURCE_TABLE_CONTACT       = "contacts"
	RESOURCE_TABLE_MONITORING    = "monitorings"
	RESOURCE_TABLE_NOTIFICATION  = "notifications"
	RESOURCE_TABLE_TELEGRAM      = "telegram"
	RESOURCE_TABLE_INITIALIZE    = "initialize"
	RESOURCE_TABLE_HEALTHZ       = "healthz"

	// User
	RESOURCE_TABLE_PERMISSION = "permissions"
	RESOURCE_TABLE_ROLE       = "roles"
	RESOURCE_TABLE_USER       = "users"

	// School
	RESOURCE_TABLE_SCHOOL   = "schools"
	RESOURCE_TABLE_DIRECTOR = "directors"
	RESOURCE_TABLE_MANAGER  = "managers"
	RESOURCE_TABLE_TEACHER  = "teachers"
	RESOURCE_TABLE_STUDENT  = "students"
	RESOURCE_TABLE_PARENT   = "parents"
	RESOURCE_TABLE_YEAR     = "years"
	RESOURCE_TABLE_COURSE   = "courses"
	RESOURCE_TABLE_EXAM     = "exams"
	RESOURCE_TABLE_MEETING  = "meetings"
	RESOURCE_TABLE_QUIZ     = "quizzes"
	RESOURCE_TABLE_RESULT   = "results"
	RESOURCE_TABLE_REPORT   = "reports"
	RESOURCE_TABLE_SCHEDULE = "schedules"
	RESOURCE_TABLE_REQUEST  = "requests"
	RESOURCE_TABLE_PAYMENT  = "payments"

	// Highschool
	RESOURCE_TABLE_HIGHSCHOOL_SECTION   = "highschool sections"
	RESOURCE_TABLE_HIGHSCHOOL_SPECIALTY = "highschool specialties"
	RESOURCE_TABLE_HIGHSCHOOL_CLASS     = "highschool classes"
	RESOURCE_TABLE_HIGHSCHOOL_QUARTER   = "highschool quarters"
	RESOURCE_TABLE_HIGHSCHOOL_SEQUENCE  = "highschool sequences"
	RESOURCE_TABLE_HIGHSCHOOL_SUBJECT   = "highschool subjects"

	// University
	RESOURCE_TABLE_UNIVERSITY_FACULTY    = "university faculties"
	RESOURCE_TABLE_UNIVERSITY_DEPARTMENT = "university departments"
	RESOURCE_TABLE_UNIVERSITY_DOMAIN     = "university domains"
	RESOURCE_TABLE_UNIVERSITY_LEVEL      = "university levels"
	RESOURCE_TABLE_UNIVERSITY_SEMESTER   = "university semesters"
	RESOURCE_TABLE_UNIVERSITY_UNIT       = "university units"
)

var RESOURCE_TABLE_LIST = []string{
	RESOURCE_TABLE_COMMUNICATION,
	RESOURCE_TABLE_CONTACT,

	RESOURCE_TABLE_PERMISSION,
	RESOURCE_TABLE_ROLE,
	RESOURCE_TABLE_USER,

	RESOURCE_TABLE_SCHOOL,
	RESOURCE_TABLE_DIRECTOR,
	RESOURCE_TABLE_MANAGER,
	RESOURCE_TABLE_TEACHER,
	RESOURCE_TABLE_STUDENT,
	RESOURCE_TABLE_PARENT,
	RESOURCE_TABLE_YEAR,
	RESOURCE_TABLE_COURSE,
	RESOURCE_TABLE_EXAM,
	RESOURCE_TABLE_MEETING,
	RESOURCE_TABLE_QUIZ,
	RESOURCE_TABLE_RESULT,
	RESOURCE_TABLE_REPORT,
	RESOURCE_TABLE_SCHEDULE,
	RESOURCE_TABLE_REQUEST,
	RESOURCE_TABLE_PAYMENT,

	RESOURCE_TABLE_HIGHSCHOOL_SECTION,
	RESOURCE_TABLE_HIGHSCHOOL_SPECIALTY,
	RESOURCE_TABLE_HIGHSCHOOL_CLASS,
	RESOURCE_TABLE_HIGHSCHOOL_QUARTER,
	RESOURCE_TABLE_HIGHSCHOOL_SEQUENCE,
	RESOURCE_TABLE_HIGHSCHOOL_SUBJECT,

	RESOURCE_TABLE_UNIVERSITY_FACULTY,
	RESOURCE_TABLE_UNIVERSITY_DEPARTMENT,
	RESOURCE_TABLE_UNIVERSITY_DOMAIN,
	RESOURCE_TABLE_UNIVERSITY_LEVEL,
	RESOURCE_TABLE_UNIVERSITY_SEMESTER,
	RESOURCE_TABLE_UNIVERSITY_UNIT,
}
