package constants

const (
	SCHOOL_TYPE_UNIVERSITY = "university"
	SCHOOL_TYPE_HIGHSCHOOL = "highschool"
)

const (
	SCHOOL_DEPLOYMENT_STATUS_INITIATED       = "initiated"
	SCHOOL_DEPLOYMENT_STATUS_PENDING         = "pending"
	SCHOOL_DEPLOYMENT_STATUS_DONE_NO_CHANGES = "done_no_changes"
	SCHOOL_DEPLOYMENT_STATUS_DONE            = "done"
	SCHOOL_DEPLOYMENT_STATUS_FAILED          = "failed"
)

const (
	SCHOOL_DEPLOYMENT_REQUEST_CREATE = "create"
	SCHOOL_DEPLOYMENT_REQUEST_UPDATE = "update"
	SCHOOL_DEPLOYMENT_REQUEST_DELETE = "delete"
)
