name: School API Production CI
run-name: ${{ github.actor }} is building school API Docker image
on:
  push:
    branches: [main] # Branch name
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  packages: write

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    env:
      CONTAINER_PROVIDER: ghcr.io
      CONTAINER_ORG: allatchimi
      CONTAINER_REPO: school-api
      CONTAINER_IMAGE: school-api
      CONTAINER_IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          ref: "main" # Branch name

      - name: Build Docker image
        run: |
          docker build ./ --file ./docker/api/Dockerfile \
          --tag ${{ env.CONTAINER_PROVIDER}}/${{ env.CONTAINER_ORG }}/${{ env.CONTAINER_REPO }}/${{ env.CONTAINER_IMAGE }}:${{ env.CONTAINER_IMAGE_TAG }} \
          --tag ${{ env.CONTAINER_PROVIDER}}/${{ env.CONTAINER_ORG }}/${{ env.CONTAINER_REPO }}/${{ env.CONTAINER_IMAGE }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: "${{ env.CONTAINER_PROVIDER}}/${{ env.CONTAINER_ORG }}/${{ env.CONTAINER_REPO }}/${{ env.CONTAINER_IMAGE }}:${{ env.CONTAINER_IMAGE_TAG }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "MEDIUM,HIGH,CRITICAL"

      - name: Login to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.CONTAINER_PROVIDER }} -u "${{ github.actor }}" --password-stdin

      - name: Push image to GitHub Docker Registry
        run: |
          docker push ${{ env.CONTAINER_PROVIDER}}/${{ env.CONTAINER_ORG }}/${{ env.CONTAINER_REPO }}/${{ env.CONTAINER_IMAGE }}:${{ env.CONTAINER_IMAGE_TAG }}
          docker push ${{ env.CONTAINER_PROVIDER}}/${{ env.CONTAINER_ORG }}/${{ env.CONTAINER_REPO }}/${{ env.CONTAINER_IMAGE }}:latest
